DATA:
  DIM: 2                                                        # data dimension
  DATA_PATH: './data/cremi/'                                    # Path to dataset
  FORMAT: '.png'
  DATASET: 'cremi'                                              # Dataset name
  IMG_SIZE: [48, 48]                                            # Input image size
  TRAIN_SAMPLES: 100
  VAL_SAMPLES: 25
  NUM_PATCH: 4                                                  # no of patch from each volume
  IN_CHANNELS: 1
  OUT_CHANNELS: 1