DATA:
  DIM: 2                                                      # data dimension
  DATA_PATH: './data/elegans_cells/'                          # Path to dataset
  FORMAT: '.png'
  DATASET: 'elegans'                                          # Dataset name
  IMG_SIZE: [48, 48]                                          # Input image size
  TRAIN_SAMPLES: 80
  VAL_SAMPLES: 20
  NUM_PATCH: 1                                                # no of patch from each volume
  IN_CHANNELS: 1
  OUT_CHANNELS: 1