DATA:
  DIM: 2                                                        # data dimension
  DATA_PATH: './data/mnist/'                                    # Path to dataset
  FORMAT: '.npy'
  DATASET: 'mnist'                                              # Dataset name
  IMG_SIZE: [48, 48]                                            # Input image size
  TRAIN_SAMPLES: 4500
  VAL_SAMPLES: 500
  NUM_PATCH: 1                                                  # no of patch from each volume
  IN_CHANNELS: 1
  OUT_CHANNELS: 1